### ISSUE TITLE
OpenID Exception?

### ISSUE THREAD

**Issue by StevePavlin** [Jessecar96/SteamAuth#5]
```Fatal error: Uncaught exception 'ErrorException' with message 'No OpenID Server found at http://steamcommunity.com/openid' in /usr/share/nginx/html/steamauth/openid.php:538 Stack trace: #0 /usr/share/nginx/html/steamauth/openid.php(671): LightOpenID->discover('http://steamcom...') #1 /usr/share/nginx/html/steamauth/SteamAuth.class.php(168): LightOpenID->authUrl() #2 /usr/share/nginx/html/page.php(12): SteamAuth->GetLoginURL() #3```

Could anyone give me a pointer as to why this happens? It causes my site to throw this error and be unable to load.

**Comment by RafalNiewinski** [comment]
This may occur when your server cannot establish connection with OpenID server or Steam OpenID Service is down and returning error (not valid openid) response.

You should secure your site for this exception because Steam Community quite often has problems.

**Comment by StevePavlin** [comment]
How should I handle this exception? Also, I can login to other OpenID sites perfectly fine when only mine returns this error on all pages that require steamauth, was I firewalled or something?

**Comment by RafalNiewinski** [comment]
If you think the problem is in your code or your server, please run example from this repository.

For handling exceptions you can put SteamAuth functions execution in try catch block.

**Comment by Jessecar96** [comment]
Yeah this happens when Steam's openid server is down. Use a try..catch to avoid this.
