### ISSUE TITLE
SessionID

### ISSUE THREAD

**Issue by ghost** [Jessecar96/SteamAuth#8]
Hello,

how Can I get my sessionID when i'm logged in with this?

**Comment by RafalNiewinski** [comment]
Please read README file again.

**Comment by ghost** [comment]
Hello,
There is only written stuff about the steam ID but i need the Session ID of the current login or am I blind?

**Comment by RafalNiewinski** [comment]
This library uses standard PHP sessions, so you can use this:

http://php.net/manual/en/function.session-id.php

**Comment by ghost** [comment]
I need the sessionID from the steamcommunity page can you help me?
